<?php

use App\Models\Warga;
use Illuminate\Database\Seeder;

class WargaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $warga = [
            [
                'id_bagian' => 6,
                'nama' => 'Sri Fanny Atmadja',
                'nik' => '3578101312860312',
                'tgl_lahir' => '1986-12-13',
                'jkel' => 'P',
                'status_kawin' => 'sudah',
                'no_kk' => '3578101312170312',
                'no_rt' => 'RT 001',
                'no_rw' => 'RW 001',
                'agama' => 'Islam',
                'created_at' => now(),
                'updated_at' => now(),
                'pendidikan' => 'Strata 1',
                'pekerjaan' => 'Karyawan Swasta',
                'kewarganegaraan' => 'WNI',
                'kedudukan_keluarga' => 'Anggota',
                'alamat' => 'Jl Rajawali 3, Surabaya, Jawa Timur',
                'alamat_ktp' => 'Jl Rajawali 3, Surabaya, Jawa Timur'
            ],
            [
                'id_bagian' => 6,
                'nama' => 'Johan Kuswoyo',
                'nik' => '3578101210840312',
                'tgl_lahir' => '1984-10-12',
                'jkel' => 'L',
                'status_kawin' => 'sudah',
                'no_kk' => '3578101312170312',
                'no_rt' => 'RT 001',
                'no_rw' => 'RW 002',
                'created_at' => now(),
                'updated_at' => now(),
                'agama' => 'Islam',
                'pendidikan' => 'Strata 1',
                'pekerjaan' => 'Karyawan Swasta',
                'kewarganegaraan' => 'WNI',
                'kedudukan_keluarga' => 'Kepala',
                'alamat' => 'Jl Rajawali 3, Surabaya, Jawa Timur',
                'alamat_ktp' => 'Jl Rajawali 3, Surabaya, Jawa Timur'
            ],
            [
                'id_bagian' => 6,
                'nama' => 'Susila Suhendra Irawan',
                'nik' => '3578102807950312',
                'tgl_lahir' => '1995-07-28',
                'jkel' => 'L',
                'status_kawin' => 'belum',
                'no_kk' => '3578101112160312',
                'no_rt' => 'RT 001',
                'no_rw' => 'RW 003',
                'created_at' => now(),
                'updated_at' => now(),
                'agama' => 'Kristen',
                'pendidikan' => 'Strata 1',
                'pekerjaan' => 'PNS',
                'kewarganegaraan' => 'WNI',
                'kedudukan_keluarga' => 'Anggota',
                'alamat' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur',
                'alamat_ktp' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur'
            ],
            [
                'id_bagian' => 6,
                'nama' => 'Bima Agung Tahyadi',
                'nik' => '3578102201910312',
                'tgl_lahir' => '1997-01-22',
                'jkel' => 'L',
                'status_kawin' => 'belum',
                'no_kk' => '3578101102160312',
                'no_rt' => 'RT 001',
                'no_rw' => 'RW 004',
                'created_at' => now(),
                'updated_at' => now(),
                'agama' => 'Islam',
                'pendidikan' => 'Strata 1',
                'pekerjaan' => 'Buruh',
                'kewarganegaraan' => 'WNI',
                'kedudukan_keluarga' => 'Anggota',
                'alamat' => 'Jl Undaan Kulon 45, Surabaya, Jawa Timur',
                'alamat_ktp' => 'Jl Undaan Kulon 45, Surabaya, Jawa Timur'
            ],
            [
                'id_bagian' => 6,
                'nama' => 'Cahaya Utami Salim',
                'nik' => '3578101607940312',
                'tgl_lahir' => '1994-07-16',
                'jkel' => 'P',
                'status_kawin' => 'belum',
                'no_kk' => '3578101102260312',
                'no_rt' => 'RT 001',
                'no_rw' => 'RW 005',
                'created_at' => now(),
                'updated_at' => now(),
                'agama' => 'Islam',
                'pendidikan' => 'Strata 1',
                'pekerjaan' => 'Wirausaha',
                'kewarganegaraan' => 'WNI',
                'kedudukan_keluarga' => 'Anggota',
                'alamat' => 'Jl Gadung 1, Surabaya, Jawa Timur',
                'alamat_ktp' => 'Jl Gadung 1, Surabaya, Jawa Timur'
            ],
            [
                'id_bagian' => 6,
                'nama' => 'Dewi Sari Wulandari',
                'nik' => '3578101502950312',
                'tgl_lahir' => '1995-02-15',
                'jkel' => 'P',
                'status_kawin' => 'belum',
                'no_kk' => '3578101102360312',
                'no_rt' => 'RT 002',
                'no_rw' => 'RW 001',
                'created_at' => now(),
                'updated_at' => now(),
                'agama' => 'Islam',
                'pendidikan' => 'Strata 1',
                'pekerjaan' => 'Karyawan Swasta',
                'kewarganegaraan' => 'WNI',
                'kedudukan_keluarga' => 'Anggota',
                'alamat' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur',
                'alamat_ktp' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur'
            ],
            [
                'id_bagian' => 6,
                'nama' => 'Eko Prasetyo',
                'nik' => '3578101502950312',
                'tgl_lahir' => '1995-02-15',
                'jkel' => 'L',
                'status_kawin' => 'belum',
                'no_kk' => '3578101102360312',
                'no_rt' => 'RT 002',
                'no_rw' => 'RW 002',
                'created_at' => now(),
                'updated_at' => now(),
                'agama' => 'Islam',
                'pendidikan' => 'Strata 1',
                'pekerjaan' => 'Karyawan Swasta',
                'kewarganegaraan' => 'WNI',
                'kedudukan_keluarga' => 'Anggota',
                'alamat' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur',
                'alamat_ktp' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur'
            ],
            [
                'id_bagian' => 6,
                'nama' => 'Fajar Hidayat',
                'nik' => '3578101502950312',
                'tgl_lahir' => '1995-02-15',
                'jkel' => 'L',
                'status_kawin' => 'belum',
                'no_kk' => '3578101102360312',
                'no_rt' => 'RT 002',
                'no_rw' => 'RW 003',
                'created_at' => now(),
                'updated_at' => now(),
                'agama' => 'Islam',
                'pendidikan' => 'Strata 1',
                'pekerjaan' => 'Karyawan Swasta',
                'kewarganegaraan' => 'WNI',
                'kedudukan_keluarga' => 'Anggota',
                'alamat' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur',
                'alamat_ktp' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur'
            ],
            [
                'id_bagian' => 6,
                'nama' => 'Gita Sari',
                'nik' => '3578101502950312',
                'tgl_lahir' => '1995-02-15',
                'jkel' => 'P',
                'status_kawin' => 'belum',
                'no_kk' => '3578101102360312',
                'no_rt' => 'RT 002',
                'no_rw' => 'RW 004',
                'created_at' => now(),
                'updated_at' => now(),
                'agama' => 'Islam',
                'pendidikan' => 'Strata 1',
                'pekerjaan' => 'Karyawan Swasta',
                'kewarganegaraan' => 'WNI',
                'kedudukan_keluarga' => 'Anggota',
                'alamat' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur',
                'alamat_ktp' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur'
            ],
            [
                'id_bagian' => 6,
                'nama' => 'Hendra Setiawan',
                'nik' => '3578101502950312',
                'tgl_lahir' => '1995-02-15',
                'jkel' => 'L',
                'status_kawin' => 'belum',
                'no_kk' => '3578101102360312',
                'no_rt' => 'RT 002',
                'no_rw' => 'RW 005',
                'created_at' => now(),
                'updated_at' => now(),
                'agama' => 'Islam',
                'pendidikan' => 'Strata 1',
                'pekerjaan' => 'Karyawan Swasta',
                'kewarganegaraan' => 'WNI',
                'kedudukan_keluarga' => 'Anggota',
                'alamat' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur',
                'alamat_ktp' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur'
            ],
            [
                'id_bagian' => 6,
                'nama' => 'Indah Permata',
                'nik' => '3578101502950312',
                'tgl_lahir' => '1995-02-15',
                'jkel' => 'P',
                'status_kawin' => 'belum',
                'no_kk' => '3578101102360312',
                'no_rt' => 'RT 003',
                'no_rw' => 'RW 001',
                'created_at' => now(),
                'updated_at' => now(),
                'agama' => 'Islam',
                'pendidikan' => 'Strata 1',
                'pekerjaan' => 'Karyawan Swasta',
                'kewarganegaraan' => 'WNI',
                'kedudukan_keluarga' => 'Anggota',
                'alamat' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur',
                'alamat_ktp' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur'
            ],
            [
                'id_bagian' => 6,
                'nama' => 'Joko Santoso',
                'nik' => '3578101502950312',
                'tgl_lahir' => '1995-02-15',
                'jkel' => 'L',
                'status_kawin' => 'belum',
                'no_kk' => '3578101102360312',
                'no_rt' => 'RT 003',
                'no_rw' => 'RW 002',
                'created_at' => now(),
                'updated_at' => now(),
                'agama' => 'Islam',
                'pendidikan' => 'Strata 1',
                'pekerjaan' => 'Karyawan Swasta',
                'kewarganegaraan' => 'WNI',
                'kedudukan_keluarga' => 'Anggota',
                'alamat' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur',
                'alamat_ktp' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur'
            ],
            [
                'id_bagian' => 6,
                'nama' => 'Kiki Sari',
                'nik' => '3578101502950312',
                'tgl_lahir' => '1995-02-15',
                'jkel' => 'P',
                'status_kawin' => 'belum',
                'no_kk' => '3578101102360312',
                'no_rt' => 'RT 003',
                'no_rw' => 'RW 003',
                'created_at' => now(),
                'updated_at' => now(),
                'agama' => 'Islam',
                'pendidikan' => 'Strata 1',
                'pekerjaan' => 'Karyawan Swasta',
                'kewarganegaraan' => 'WNI',
                'kedudukan_keluarga' => 'Anggota',
                'alamat' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur',
                'alamat_ktp' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur'
            ],
            [
                'id_bagian' => 6,
                'nama' => 'Lina Sari',
                'nik' => '3578101502950312',
                'tgl_lahir' => '1995-02-15',
                'jkel' => 'P',
                'status_kawin' => 'belum',
                'no_kk' => '3578101102360312',
                'no_rt' => 'RT 003',
                'no_rw' => 'RW 004',
                'created_at' => now(),
                'updated_at' => now(),
                'agama' => 'Islam',
                'pendidikan' => 'Strata 1',
                'pekerjaan' => 'Karyawan Swasta',
                'kewarganegaraan' => 'WNI',
                'kedudukan_keluarga' => 'Anggota',
                'alamat' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur',
                'alamat_ktp' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur'
            ],
            [
                'id_bagian' => 6,
                'nama' => 'Maya Sari',
                'nik' => '3578101502950312',
                'tgl_lahir' => '1995-02-15',
                'jkel' => 'P',
                'status_kawin' => 'belum',
                'no_kk' => '3578101102360312',
                'no_rt' => 'RT 003',
                'no_rw' => 'RW 005',
                'created_at' => now(),
                'updated_at' => now(),
                'agama' => 'Islam',
                'pendidikan' => 'Strata 1',
                'pekerjaan' => 'Karyawan Swasta',
                'kewarganegaraan' => 'WNI',
                'kedudukan_keluarga' => 'Anggota',
                'alamat' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur',
                'alamat_ktp' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur'
            ],
            [
                'id_bagian' => 6,
                'nama' => 'Nina Sari',
                'nik' => '3578101502950312',
                'tgl_lahir' => '1995-02-15',
                'jkel' => 'P',
                'status_kawin' => 'belum',
                'no_kk' => '3578101102360312',
                'no_rt' => 'RT 004',
                'no_rw' => 'RW 001',
                'created_at' => now(),
                'updated_at' => now(),
                'agama' => 'Islam',
                'pendidikan' => 'Strata 1',
                'pekerjaan' => 'Karyawan Swasta',
                'kewarganegaraan' => 'WNI',
                'kedudukan_keluarga' => 'Anggota',
                'alamat' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur',
                'alamat_ktp' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur'
            ],
            [
                'id_bagian' => 6,
                'nama' => 'Oki Setiawan',
                'nik' => '3578101502950312',
                'tgl_lahir' => '1995-02-15',
                'jkel' => 'L',
                'status_kawin' => 'belum',
                'no_kk' => '3578101102360312',
                'no_rt' => 'RT 004',
                'no_rw' => 'RW 002',
                'created_at' => now(),
                'updated_at' => now(),
                'agama' => 'Islam',
                'pendidikan' => 'Strata 1',
                'pekerjaan' => 'Karyawan Swasta',
                'kewarganegaraan' => 'WNI',
                'kedudukan_keluarga' => 'Anggota',
                'alamat' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur',
                'alamat_ktp' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur'
            ],
            [
                'id_bagian' => 6,
                'nama' => 'Putri Sari',
                'nik' => '3578101502950312',
                'tgl_lahir' => '1995-02-15',
                'jkel' => 'P',
                'status_kawin' => 'belum',
                'no_kk' => '3578101102360312',
                'no_rt' => 'RT 004',
                'no_rw' => 'RW 003',
                'created_at' => now(),
                'updated_at' => now(),
                'agama' => 'Islam',
                'pendidikan' => 'Strata 1',
                'pekerjaan' => 'Karyawan Swasta',
                'kewarganegaraan' => 'WNI',
                'kedudukan_keluarga' => 'Anggota',
                'alamat' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur',
                'alamat_ktp' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur'
            ],
            [
                'id_bagian' => 6,
                'nama' => 'Rudi Setiawan',
                'nik' => '3578101502950312',
                'tgl_lahir' => '1995-02-15',
                'jkel' => 'L',
                'status_kawin' => 'belum',
                'no_kk' => '3578101102360312',
                'no_rt' => 'RT 004',
                'no_rw' => 'RW 004',
                'created_at' => now(),
                'updated_at' => now(),
                'agama' => 'Islam',
                'pendidikan' => 'Strata 1',
                'pekerjaan' => 'Karyawan Swasta',
                'kewarganegaraan' => 'WNI',
                'kedudukan_keluarga' => 'Anggota',
                'alamat' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur',
                'alamat_ktp' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur'
            ],
            [
                'id_bagian' => 6,
                'nama' => 'Siti Aisyah',
                'nik' => '3578101502950312',
                'tgl_lahir' => '1995-02-15',
                'jkel' => 'P',
                'status_kawin' => 'belum',
                'no_kk' => '3578101102360312',
                'no_rt' => 'RT 004',
                'no_rw' => 'RW 005',
                'created_at' => now(),
                'updated_at' => now(),
                'agama' => 'Islam',
                'pendidikan' => 'Strata 1',
                'pekerjaan' => 'Karyawan Swasta',
                'kewarganegaraan' => 'WNI',
                'kedudukan_keluarga' => 'Anggota',
                'alamat' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur',
                'alamat_ktp' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur'
            ],
            [
                'id_bagian' => 6,
                'nama' => 'Tina Sari',
                'nik' => '3578101502950312',
                'tgl_lahir' => '1995-02-15',
                'jkel' => 'P',
                'status_kawin' => 'belum',
                'no_kk' => '3578101102360312',
                'no_rt' => 'RT 005',
                'no_rw' => 'RW 001',
                'created_at' => now(),
                'updated_at' => now(),
                'agama' => 'Islam',
                'pendidikan' => 'Strata 1',
                'pekerjaan' => 'Karyawan Swasta',
                'kewarganegaraan' => 'WNI',
                'kedudukan_keluarga' => 'Anggota',
                'alamat' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur',
                'alamat_ktp' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur'
            ],
            [
                'id_bagian' => 6,
                'nama' => 'Udin Setiawan',
                'nik' => '3578101502950312',
                'tgl_lahir' => '1995-02-15',
                'jkel' => 'L',
                'status_kawin' => 'belum',
                'no_kk' => '3578101102360312',
                'no_rt' => 'RT 005',
                'no_rw' => 'RW 002',
                'created_at' => now(),
                'updated_at' => now(),
                'agama' => 'Islam',
                'pendidikan' => 'Strata 1',
                'pekerjaan' => 'Karyawan Swasta',
                'kewarganegaraan' => 'WNI',
                'kedudukan_keluarga' => 'Anggota',
                'alamat' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur',
                'alamat_ktp' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur'
            ],
            [
                'id_bagian' => 6,
                'nama' => 'Vina Sari',
                'nik' => '3578101502950312',
                'tgl_lahir' => '1995-02-15',
                'jkel' => 'P',
                'status_kawin' => 'belum',
                'no_kk' => '3578101102360312',
                'no_rt' => 'RT 005',
                'no_rw' => 'RW 003',
                'created_at' => now(),
                'updated_at' => now(),
                'agama' => 'Islam',
                'pendidikan' => 'Strata 1',
                'pekerjaan' => 'Karyawan Swasta',
                'kewarganegaraan' => 'WNI',
                'kedudukan_keluarga' => 'Anggota',
                'alamat' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur',
                'alamat_ktp' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur'
            ],
            [
                'id_bagian' => 6,
                'nama' => 'Wahyu Setiawan',
                'nik' => '3578101502950312',
                'tgl_lahir' => '1995-02-15',
                'jkel' => 'L',
                'status_kawin' => 'belum',
                'no_kk' => '3578101102360312',
                'no_rt' => 'RT 005',
                'no_rw' => 'RW 004',
                'created_at' => now(),
                'updated_at' => now(),
                'agama' => 'Islam',
                'pendidikan' => 'Strata 1',
                'pekerjaan' => 'Karyawan Swasta',
                'kewarganegaraan' => 'WNI',
                'kedudukan_keluarga' => 'Anggota',
                'alamat' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur',
                'alamat_ktp' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur'
            ],
            [
                'id_bagian' => 6,
                'nama' => 'Yuni Sari',
                'nik' => '3578101502950312',
                'tgl_lahir' => '1995-02-15',
                'jkel' => 'P',
                'status_kawin' => 'belum',
                'no_kk' => '3578101102360312',
                'no_rt' => 'RT 005',
                'no_rw' => 'RW 005',
                'created_at' => now(),
                'updated_at' => now(),
                'agama' => 'Islam',
                'pendidikan' => 'Strata 1',
                'pekerjaan' => 'Karyawan Swasta',
                'kewarganegaraan' => 'WNI',
                'kedudukan_keluarga' => 'Anggota',
                'alamat' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur',
                'alamat_ktp' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur'
            ],
            [
                'id_bagian' => 6,
                'nama' => 'Zainal Abidin',
                'nik' => '3578101502950312',
                'tgl_lahir' => '1995-02-15',
                'jkel' => 'L',
                'status_kawin' => 'belum',
                'no_kk' => '3578101102360312',
                'no_rt' => 'RT 006',
                'no_rw' => 'RW 001',
                'created_at' => now(),
                'updated_at' => now(),
                'agama' => 'Islam',
                'pendidikan' => 'Strata 1',
                'pekerjaan' => 'Karyawan Swasta',
                'kewarganegaraan' => 'WNI',
                'kedudukan_keluarga' => 'Anggota',
                'alamat' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur',
                'alamat_ktp' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur'
            ],
            [
                'id_bagian' => 6,
                'nama' => 'Ayu Sari',
                'nik' => '3578101502950312',
                'tgl_lahir' => '1995-02-15',
                'jkel' => 'P',
                'status_kawin' => 'belum',
                'no_kk' => '3578101102360312',
                'no_rt' => 'RT 006',
                'no_rw' => 'RW 002',
                'created_at' => now(),
                'updated_at' => now(),
                'agama' => 'Islam',
                'pendidikan' => 'Strata 1',
                'pekerjaan' => 'Karyawan Swasta',
                'kewarganegaraan' => 'WNI',
                'kedudukan_keluarga' => 'Anggota',
                'alamat' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur',
                'alamat_ktp' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur'
            ],
            [
                'id_bagian' => 6,
                'nama' => 'Budi Setiawan',
                'nik' => '3578101502950312',
                'tgl_lahir' => '1995-02-15',
                'jkel' => 'L',
                'status_kawin' => 'belum',
                'no_kk' => '3578101102360312',
                'no_rt' => 'RT 006',
                'no_rw' => 'RW 003',
                'created_at' => now(),
                'updated_at' => now(),
                'agama' => 'Islam',
                'pendidikan' => 'Strata 1',
                'pekerjaan' => 'Karyawan Swasta',
                'kewarganegaraan' => 'WNI',
                'kedudukan_keluarga' => 'Anggota',
                'alamat' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur',
                'alamat_ktp' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur'
            ],
            [
                'id_bagian' => 6,
                'nama' => 'Cindy Sari',
                'nik' => '3578101502950312',
                'tgl_lahir' => '1995-02-15',
                'jkel' => 'P',
                'status_kawin' => 'belum',
                'no_kk' => '3578101102360312',
                'no_rt' => 'RT 006',
                'no_rw' => 'RW 004',
                'created_at' => now(),
                'updated_at' => now(),
                'agama' => 'Islam',
                'pendidikan' => 'Strata 1',
                'pekerjaan' => 'Karyawan Swasta',
                'kewarganegaraan' => 'WNI',
                'kedudukan_keluarga' => 'Anggota',
                'alamat' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur',
                'alamat_ktp' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur'
            ],
            [
                'id_bagian' => 6,
                'nama' => 'Dani Setiawan',
                'nik' => '3578101502950312',
                'tgl_lahir' => '1995-02-15',
                'jkel' => 'L',
                'status_kawin' => 'belum',
                'no_kk' => '3578101102360312',
                'no_rt' => 'RT 006',
                'no_rw' => 'RW 005',
                'created_at' => now(),
                'updated_at' => now(),
                'agama' => 'Islam',
                'pendidikan' => 'Strata 1',
                'pekerjaan' => 'Karyawan Swasta',
                'kewarganegaraan' => 'WNI',
                'kedudukan_keluarga' => 'Anggota',
                'alamat' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur',
                'alamat_ktp' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur'
            ],
            [
                'id_bagian' => 6,
                'nama' => 'Eka Sari',
                'nik' => '3578101502950312',
                'tgl_lahir' => '1995-02-15',
                'jkel' => 'P',
                'status_kawin' => 'belum',
                'no_kk' => '3578101102360312',
                'no_rt' => 'RT 007',
                'no_rw' => 'RW 001',
                'created_at' => now(),
                'updated_at' => now(),
                'agama' => 'Islam',
                'pendidikan' => 'Strata 1',
                'pekerjaan' => 'Karyawan Swasta',
                'kewarganegaraan' => 'WNI',
                'kedudukan_keluarga' => 'Anggota',
                'alamat' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur',
                'alamat_ktp' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur'
            ],
            [
                'id_bagian' => 6,
                'nama' => 'Fani Setiawan',
                'nik' => '3578101502950312',
                'tgl_lahir' => '1995-02-15',
                'jkel' => 'L',
                'status_kawin' => 'belum',
                'no_kk' => '3578101102360312',
                'no_rt' => 'RT 007',
                'no_rw' => 'RW 002',
                'created_at' => now(),
                'updated_at' => now(),
                'agama' => 'Islam',
                'pendidikan' => 'Strata 1',
                'pekerjaan' => 'Karyawan Swasta',
                'kewarganegaraan' => 'WNI',
                'kedudukan_keluarga' => 'Anggota',
                'alamat' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur',
                'alamat_ktp' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur'
            ],
            [
                'id_bagian' => 6,
                'nama' => 'Gina Sari',
                'nik' => '3578101502950312',
                'tgl_lahir' => '1995-02-15',
                'jkel' => 'P',
                'status_kawin' => 'belum',
                'no_kk' => '3578101102360312',
                'no_rt' => 'RT 007',
                'no_rw' => 'RW 003',
                'created_at' => now(),
                'updated_at' => now(),
                'agama' => 'Islam',
                'pendidikan' => 'Strata 1',
                'pekerjaan' => 'Karyawan Swasta',
                'kewarganegaraan' => 'WNI',
                'kedudukan_keluarga' => 'Anggota',
                'alamat' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur',
                'alamat_ktp' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur'
            ],
            [
                'id_bagian' => 6,
                'nama' => 'Hani Setiawan',
                'nik' => '3578101502950312',
                'tgl_lahir' => '1995-02-15',
                'jkel' => 'L',
                'status_kawin' => 'belum',
                'no_kk' => '3578101102360312',
                'no_rt' => 'RT 007',
                'no_rw' => 'RW 004',
                'created_at' => now(),
                'updated_at' => now(),
                'agama' => 'Islam',
                'pendidikan' => 'Strata 1',
                'pekerjaan' => 'Karyawan Swasta',
                'kewarganegaraan' => 'WNI',
                'kedudukan_keluarga' => 'Anggota',
                'alamat' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur',
                'alamat_ktp' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur'
            ],
            [
                'id_bagian' => 6,
                'nama' => 'Ika Sari',
                'nik' => '3578101502950312',
                'tgl_lahir' => '1995-02-15',
                'jkel' => 'P',
                'status_kawin' => 'belum',
                'no_kk' => '3578101102360312',
                'no_rt' => 'RT 007',
                'no_rw' => 'RW 005',
                'created_at' => now(),
                'updated_at' => now(),
                'agama' => 'Islam',
                'pendidikan' => 'Strata 1',
                'pekerjaan' => 'Karyawan Swasta',
                'kewarganegaraan' => 'WNI',
                'kedudukan_keluarga' => 'Anggota',
                'alamat' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur',
                'alamat_ktp' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur'
            ],
            [
                'id_bagian' => 6,
                'nama' => 'Joni Setiawan',
                'nik' => '3578101502950312',
                'tgl_lahir' => '1995-02-15',
                'jkel' => 'L',
                'status_kawin' => 'belum',
                'no_kk' => '3578101102360312',
                'no_rt' => 'RT 008',
                'no_rw' => 'RW 001',
                'created_at' => now(),
                'updated_at' => now(),
                'agama' => 'Islam',
                'pendidikan' => 'Strata 1',
                'pekerjaan' => 'Karyawan Swasta',
                'kewarganegaraan' => 'WNI',
                'kedudukan_keluarga' => 'Anggota',
                'alamat' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur',
                'alamat_ktp' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur'
            ],
            [
                'id_bagian' => 6,
                'nama' => 'Kris Sari',
                'nik' => '3578101502950312',
                'tgl_lahir' => '1995-02-15',
                'jkel' => 'P',
                'status_kawin' => 'belum',
                'no_kk' => '3578101102360312',
                'no_rt' => 'RT 008',
                'no_rw' => 'RW 002',
                'created_at' => now(),
                'updated_at' => now(),
                'agama' => 'Islam',
                'pendidikan' => 'Strata 1',
                'pekerjaan' => 'Karyawan Swasta',
                'kewarganegaraan' => 'WNI',
                'kedudukan_keluarga' => 'Anggota',
                'alamat' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur',
                'alamat_ktp' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur'
            ],
            [
                'id_bagian' => 6,
                'nama' => 'Lukman Setiawan',
                'nik' => '3578101502950312',
                'tgl_lahir' => '1995-02-15',
                'jkel' => 'L',
                'status_kawin' => 'belum',
                'no_kk' => '3578101102360312',
                'no_rt' => 'RT 008',
                'no_rw' => 'RW 003',
                'created_at' => now(),
                'updated_at' => now(),
                'agama' => 'Islam',
                'pendidikan' => 'Strata 1',
                'pekerjaan' => 'Karyawan Swasta',
                'kewarganegaraan' => 'WNI',
                'kedudukan_keluarga' => 'Anggota',
                'alamat' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur',
                'alamat_ktp' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur'
            ],
            [
                'id_bagian' => 6,
                'nama' => 'Mira Sari',
                'nik' => '3578101502950312',
                'tgl_lahir' => '1995-02-15',
                'jkel' => 'P',
                'status_kawin' => 'belum',
                'no_kk' => '3578101102360312',
                'no_rt' => 'RT 008',
                'no_rw' => 'RW 004',
                'created_at' => now(),
                'updated_at' => now(),
                'agama' => 'Islam',
                'pendidikan' => 'Strata 1',
                'pekerjaan' => 'Karyawan Swasta',
                'kewarganegaraan' => 'WNI',
                'kedudukan_keluarga' => 'Anggota',
                'alamat' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur',
                'alamat_ktp' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur'
            ],
            [
                'id_bagian' => 6,
                'nama' => 'Nadia Setiawan',
                'nik' => '3578101502950312',
                'tgl_lahir' => '1995-02-15',
                'jkel' => 'P',
                'status_kawin' => 'belum',
                'no_kk' => '3578101102360312',
                'no_rt' => 'RT 008',
                'no_rw' => 'RW 005',
                'created_at' => now(),
                'updated_at' => now(),
                'agama' => 'Islam',
                'pendidikan' => 'Strata 1',
                'pekerjaan' => 'Karyawan Swasta',
                'kewarganegaraan' => 'WNI',
                'kedudukan_keluarga' => 'Anggota',
                'alamat' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur',
                'alamat_ktp' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur'
            ],
            [
                'id_bagian' => 6,
                'nama' => 'Omar Setiawan',
                'nik' => '3578101502950312',
                'tgl_lahir' => '1995-02-15',
                'jkel' => 'L',
                'status_kawin' => 'belum',
                'no_kk' => '3578101102360312',
                'no_rt' => 'RT 009',
                'no_rw' => 'RW 001',
                'created_at' => now(),
                'updated_at' => now(),
                'agama' => 'Islam',
                'pendidikan' => 'Strata 1',
                'pekerjaan' => 'Karyawan Swasta',
                'kewarganegaraan' => 'WNI',
                'kedudukan_keluarga' => 'Anggota',
                'alamat' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur',
                'alamat_ktp' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur'
            ],
            [
                'id_bagian' => 6,
                'nama' => 'Putu Sari',
                'nik' => '3578101502950312',
                'tgl_lahir' => '1995-02-15',
                'jkel' => 'P',
                'status_kawin' => 'belum',
                'no_kk' => '3578101102360312',
                'no_rt' => 'RT 009',
                'no_rw' => 'RW 002',
                'created_at' => now(),
                'updated_at' => now(),
                'agama' => 'Islam',
                'pendidikan' => 'Strata 1',
                'pekerjaan' => 'Karyawan Swasta',
                'kewarganegaraan' => 'WNI',
                'kedudukan_keluarga' => 'Anggota',
                'alamat' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur',
                'alamat_ktp' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur'
            ],
            [
                'id_bagian' => 6,
                'nama' => 'Qori Setiawan',
                'nik' => '3578101502950312',
                'tgl_lahir' => '1995-02-15',
                'jkel' => 'L',
                'status_kawin' => 'belum',
                'no_kk' => '3578101102360312',
                'no_rt' => 'RT 009',
                'no_rw' => 'RW 003',
                'created_at' => now(),
                'updated_at' => now(),
                'agama' => 'Islam',
                'pendidikan' => 'Strata 1',
                'pekerjaan' => 'Karyawan Swasta',
                'kewarganegaraan' => 'WNI',
                'kedudukan_keluarga' => 'Anggota',
                'alamat' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur',
                'alamat_ktp' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur'
            ],
            [
                'id_bagian' => 6,
                'nama' => 'Rina Sari',
                'nik' => '3578101502950312',
                'tgl_lahir' => '1995-02-15',
                'jkel' => 'P',
                'status_kawin' => 'belum',
                'no_kk' => '3578101102360312',
                'no_rt' => 'RT 009',
                'no_rw' => 'RW 004',
                'created_at' => now(),
                'updated_at' => now(),
                'agama' => 'Islam',
                'pendidikan' => 'Strata 1',
                'pekerjaan' => 'Karyawan Swasta',
                'kewarganegaraan' => 'WNI',
                'kedudukan_keluarga' => 'Anggota',
                'alamat' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur',
                'alamat_ktp' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur'
            ],
            [
                'id_bagian' => 6,
                'nama' => 'Sari Setiawan',
                'nik' => '3578101502950312',
                'tgl_lahir' => '1995-02-15',
                'jkel' => 'P',
                'status_kawin' => 'belum',
                'no_kk' => '3578101102360312',
                'no_rt' => 'RT 009',
                'no_rw' => 'RW 005',
                'created_at' => now(),
                'updated_at' => now(),
                'agama' => 'Islam',
                'pendidikan' => 'Strata 1',
                'pekerjaan' => 'Karyawan Swasta',
                'kewarganegaraan' => 'WNI',
                'kedudukan_keluarga' => 'Anggota',
                'alamat' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur',
                'alamat_ktp' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur'
            ],
            [
                'id_bagian' => 6,
                'nama' => 'Tari Sari',
                'nik' => '3578101502950312',
                'tgl_lahir' => '1995-02-15',
                'jkel' => 'P',
                'status_kawin' => 'belum',
                'no_kk' => '3578101102360312',
                'no_rt' => 'RT 010',
                'no_rw' => 'RW 001',
                'created_at' => now(),
                'updated_at' => now(),
                'agama' => 'Islam',
                'pendidikan' => 'Strata 1',
                'pekerjaan' => 'Karyawan Swasta',
                'kewarganegaraan' => 'WNI',
                'kedudukan_keluarga' => 'Anggota',
                'alamat' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur',
                'alamat_ktp' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur'
            ],
            [
                'id_bagian' => 6,
                'nama' => 'Umi Setiawan',
                'nik' => '3578101502950312',
                'tgl_lahir' => '1995-02-15',
                'jkel' => 'P',
                'status_kawin' => 'belum',
                'no_kk' => '3578101102360312',
                'no_rt' => 'RT 010',
                'no_rw' => 'RW 002',
                'created_at' => now(),
                'updated_at' => now(),
                'agama' => 'Islam',
                'pendidikan' => 'Strata 1',
                'pekerjaan' => 'Karyawan Swasta',
                'kewarganegaraan' => 'WNI',
                'kedudukan_keluarga' => 'Anggota',
                'alamat' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur',
                'alamat_ktp' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur'
            ],
            [
                'id_bagian' => 6,
                'nama' => 'Vivi Sari',
                'nik' => '3578101502950312',
                'tgl_lahir' => '1995-02-15',
                'jkel' => 'P',
                'status_kawin' => 'belum',
                'no_kk' => '3578101102360312',
                'no_rt' => 'RT 010',
                'no_rw' => 'RW 003',
                'created_at' => now(),
                'updated_at' => now(),
                'agama' => 'Islam',
                'pendidikan' => 'Strata 1',
                'pekerjaan' => 'Karyawan Swasta',
                'kewarganegaraan' => 'WNI',
                'kedudukan_keluarga' => 'Anggota',
                'alamat' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur',
                'alamat_ktp' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur'
            ],
            [
                'id_bagian' => 6,
                'nama' => 'Wira Setiawan',
                'nik' => '3578101502950312',
                'tgl_lahir' => '1995-02-15',
                'jkel' => 'L',
                'status_kawin' => 'belum',
                'no_kk' => '3578101102360312',
                'no_rt' => 'RT 010',
                'no_rw' => 'RW 004',
                'created_at' => now(),
                'updated_at' => now(),
                'agama' => 'Islam',
                'pendidikan' => 'Strata 1',
                'pekerjaan' => 'Karyawan Swasta',
                'kewarganegaraan' => 'WNI',
                'kedudukan_keluarga' => 'Anggota',
                'alamat' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur',
                'alamat_ktp' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur'
            ],
            [
                'id_bagian' => 6,
                'nama' => 'Xena Sari',
                'nik' => '3578101502950312',
                'tgl_lahir' => '1995-02-15',
                'jkel' => 'P',
                'status_kawin' => 'belum',
                'no_kk' => '3578101102360312',
                'no_rt' => 'RT 010',
                'no_rw' => 'RW 005',
                'created_at' => now(),
                'updated_at' => now(),
                'agama' => 'Islam',
                'pendidikan' => 'Strata 1',
                'pekerjaan' => 'Karyawan Swasta',
                'kewarganegaraan' => 'WNI',
                'kedudukan_keluarga' => 'Anggota',
                'alamat' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur',
                'alamat_ktp' => 'Jl Kalianak Tmr 179, Surabaya, Jawa Timur'
            ]
        ];

        foreach ($warga as $value) {
            Warga::create($value);
        }
    }
}
